### ISSUE TITLE
system growth 

### ISSUE THREAD

**Issue by krosza** [Augmint/augmint-sim#13]
by default the system (issued ACD) should grow steadily, the loan to deposit ratio ( probably better too rename to  Loan to Lock ratio ) increase help a bit but it cannot be realistically more than  max  2-3, somehow a system has a bias against growth

**Comment by szerintedmi** [comment]
There are multiple params for this now.
For locks (introduced in this commit: https://github.com/DecentLabs/augmint-sim/commit/bd7df9a4f9a4b2b778e465ac59ed01d7becd03e8) there are two params for every actor:
```
ETH_BALANCE_GROWTH_PA: 0 /* ETH balance  grows daily by pa. % to simulate growth */,
USD_BALANCE_GROWTH_PA: 0.3 /* USD balance grows daily by pa. % to simulate growth */
```
Because the locker calculates the lock amount from their USD balance this above means a 30% increase pa. 

For loans we needed a different approach (introduced in https://github.com/DecentLabs/augmint-sim/commit/26803bdb0486945ac64ed3793935f0c071e53688). 
We could use the ETH balance of the borrower as a basis for the loan demand.  But becauase of the high ETH/USD volatility there are additional params to control loan demand:
```
WANTS_TO_BORROW_AMOUNT: 10000, // how much they want to borrow
WANTS_TO_BORROW_AMOUNT_GROWTH_PA: 0.5, // increase in demand % pa.
```
This above is limited by the borrower actor's initial ETH balance but it's set to high for now: 
```
balances: {
                eth: 500000 // unlimited ETH - demand adjusted with params
            },
```

Even with all these settings I couldn't really set the system to grow significantly so we should discuss the assumptions here.
